# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "minisyntax"
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Nico Hagenburger"]
  s.date = "2012-12-06"
  s.description = "A simple powerful syntax highlighter with minimal HTML output"
  s.email = "nico@hagenburger.net"
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "MIT-LICENSE.txt",
    "README.md",
    "Rakefile",
    "lib/minisyntax.rb",
    "lib/minisyntax/highlighter.rb",
    "lib/minisyntax/highlighter/bash.rb",
    "lib/minisyntax/highlighter/command_line.rb",
    "lib/minisyntax/highlighter/css.rb",
    "lib/minisyntax/highlighter/erb.rb",
    "lib/minisyntax/highlighter/haml.rb",
    "lib/minisyntax/highlighter/html.rb",
    "lib/minisyntax/highlighter/javascript.rb",
    "lib/minisyntax/highlighter/php.rb",
    "lib/minisyntax/highlighter/ruby.rb",
    "lib/minisyntax/highlighter/yaml.rb",
    "lib/minisyntax/integration/rack.rb",
    "minisyntax.gemspec",
    "spec/minisyntax_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/hagenburger/minisyntax"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "A simple powerful syntax highlighter with minimal HTML output"
  s.test_files = [
    "spec/minisyntax_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<nokogiri>, ["~> 1.4.4"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<nokogiri>, ["~> 1.4.4"])
  end
end

